---
title: Use cases for APEx Project Tools
---

The APEx Project Tools are designed to support a wide range of activities within the EO community, from project
promotion and user support to data visualisation, data analytics, and data processing. By providing managed,
configurable environments, these services facilitate the effective sharing, maintenance, and utilisation of project
results, ensuring they remain readily accessible and usable for extended periods.

This section provides an initial outline of the primary use cases for APEx Project Tools, demonstrating how they address
the specific needs and challenges faced by users and project managers in the EO domain. Each use case highlights the
relevant components of the APEx tools, detailing how they work together to provide robust solutions for various tasks.

From promoting EO projects through interactive portals to supporting users with personalised workspaces and
comprehensive documentation, the APEx Project Tools are designed to enhance productivity and foster collaboration. Data
visualisation tools enable users to interpret and communicate insights effectively, while advanced data analytics
environments provide the computational power and tools necessary for complex analyses. Data processing workflows are
streamlined through secure, scalable environments, ensuring that users can handle large volumes of EO data efficiently.

It is important to highlight that the APEx Project Tools can be combined in different ways to create a flexible
collaborative project environments. This gives projects the flexibility to adapt the tools based on their needs. For
example, they can choose to make the project portal as their main entry point for both project members and their
community, linking to the different APEx tools from within the main website. Alternatevely, projects can decide to only
keep the project portal for public communication and dissimenation, while having the user workspaces only visible for
the project members. In essence, the APEx Project Tools provide an a la carte approach for setting up and configuring
your project environment based on your needs.

To explore the possiblities, the following use cases provide detailed scenarios of how the APEx Project Tools can be
leveraged to meet the diverse needs of the EO community, maximising the impact of EO research and applications.

## Use Case 1 - Project Promotion

### Description

Promote EO projects by providing a centralised, customisable portal that showcases project outcomes, visualisations, and
data products. This use case supports the dissemination and accessibility of project results to a broader audience,
including stakeholders, policymakers, and the general public.

### Key Components

* [**Project Portal**](project_portal.md)\
  Provides dynamic instantiation using Drupal, allowing project managers to create and maintain a visually appealing and
  informative site.
* [**Geospatial Explorer**](geospatial_explorer.md)\
  Create an online dashboard to present key metrics and visualisations.
* [**Documentation Portal**](documentation.qmd)\
  Customizable portals using the Quarto framework for detailed project documentation and interactive visualisations.
* [**User Forum**](forum.md)\
  Supports community engagement and discussions around the project outcomes.

```{mermaid}
%%| label: fig-tools-usecase2
%%| fig-cap: "APEx Project Tools - User Support"
flowchart TD ""
    subgraph Public Environment
      A(Project Portal) -->|Links to| B(Geospatial<br/>Explorer)
      A -->|Links to| C(Documentation<br/> Portal)
      A -->|Links to| D(User<br/> Forum)
    end

    class A,B,C,D apexService
    click A href "./project_portal.html" _blank
    click B href "./geospatial_explorer.html" _blank
    click C href "./documentation.html" _blank
    click D href "./forum.html" _blank
```

### Expected Benefits

* Increased visibility and impact of EO projects.
* Enhanced stakeholder engagement through accessible and interactive content.
* Long-term maintenance and accessibility of project results.

## Use Case 2- User Support

### Description

Provide comprehensive support to users, enabling them to interact with EO data, tools, and services effectively. This
use case focuses on offering personalised and collaborative environments where the project PI or their team can seek
help, share knowledge, and collaborate on EO applications.

### Key Components

* [**Project Portal**](project_portal.md)\
  Provides dynamic instantiation using Drupal, allowing project managers to create and maintain a visually appealing and
  informative site.
* [**User Forum**](forum.md)\
  An on-demand service based on Discourse, facilitating user discussions, support queries, and community-driven
  solutions.
* [**Documentation Portal**](documentation.qmd)\
  Comprehensive documentation and tutorial materials to assist users in navigating and utilising the services.
* [**User Workspace**](user_workspace.md)\
  Secure and personalised environments allow users to store, share, and manage their data and work.
* [**Interactive Development Environment (IDE)**](ide.md)\
  Leveraging VS Code Server, these environments are tailored for EO tasks and provide development tools.

```{mermaid}
%%| label: fig-tools-usecase2
%%| fig-cap: "APEx Project Tools - User Support"
flowchart TD ""
    subgraph Project Environment
      UW(User Workspace) --> |Activate| IDE(Interactive Development<br/> Environment)
    end
    subgraph Public Environment
      A(Project Portal) -->|Links to| C(Documentation<br/> Portal)
      A -->|Links to| D(User<br/> Forum)
    end

    class UW,IDE,A,C,D apexService
    click A href "./project_portal.html" _blank
    click C href "./documentation.html" _blank
    click D href "./forum.html" _blank
    click UW href "./user_workspace.html" _blank
    click IDE href "./ide.html" _blank
```

### Expected Benefits

* Improved user satisfaction and productivity through robust support mechanisms.
* Enhanced community engagement and knowledge sharing.
* Efficient troubleshooting and problem-solving through community forums.

## Use Case 3 - Data Visualization

### Use Case Description

Enable users to visualise EO data in meaningful and interactive ways. This use case supports both public and
project-specific visualisations, helping users to interpret and communicate data insights effectively.

### Key Components

* [**Geospatial Explorer**](geospatial_explorer.md)\
  Functional enhancements to provide interactive and real-time data visualisations, supporting both raster and tabular
  data visualisation.
* [**Project Portal**](project_portal.md)\
  Integration of visualisations into project portals to showcase data insights.
* [**Documentation Portal**](documentation.qmd)\
  Interactive visualisations within documentation to explain data findings and methodologies.

```{mermaid}
%%| label: fig-tools-usecase3
%%| fig-cap: "APEx Project Tools - Data Visualization"
flowchart TD ""
    subgraph Public Environment
      A(Project Portal) -->|Links to| B(Geospatial<br/>Explorer)
      A -->|Links to| C(Documentation<br/> Portal)
    end

    class A,B,C apexService
    click A href "./project_portal.html" _blank
    click B href "./geospatial_explorer.html" _blank
    click C href "./documentation.html" _blank
```

### Expected Benefits

* Enhanced understanding and interpretation of EO data.
* Improved data communication and storytelling capabilities.
* Increased engagement through interactive and visually appealing content.

## Use Case 4 - Data Analytics

### Description

Support advanced data analytics workflows, enabling users to analyse EO data efficiently. This use case focuses on
providing powerful tools and environments for data processing and statistical analysis.

### Key Components

* [**Interactive Development Environment (IDE)**](ide.md)\
  Equipped with tools for data analysis, statistical computation, and machine learning, leveraging the capabilities of
  VS Code Server.
* [**User Workspace**](user_workspace.md)\
  Secure and scalable environments for conducting extensive data analysis.
* [**Product Catalogue**](catalog.qmd)\
  A STAC catalogue providing easy access to EO datasets and streamlining the data ingestion process.
* [**Geospatial Explorer**](geospatial_explorer.md)\
  Integration with analytics tools to provide real-time visualisations of analytical results.

```{mermaid}
%%| label: fig-tools-usecase4
%%| fig-cap: "APEx Project Tools - Data Analytics"
flowchart TD ""
    subgraph Project Environment
      UW(User Workspace) --> |Activate| IDE(Interactive Development<br/> Environment)
    end
    subgraph Public Environment
      A(Project Portal) -->|Links to| B(Geospatial<br/>Explorer)
      B -->|Visualizes| C(Product<br/>Catalogue)
      A -->|Links to| C
    end

    IDE -->|Publish| C

    class UW,IDE,A,B,C apexService
    click A href "./project_portal.html" _blank
    click B href "./geospatial_explorer.html" _blank
    click C href "./catalog.html" _blank
    click UW href "./user_workspace.html" _blank
    click IDE href "./ide.html" _blank
```

### Expected Benefits

* Enhanced analytical capabilities and data-driven insights.
* Efficient processing and analysis of large EO datasets.
* Streamlined workflows from data ingestion to analysis and visualisation.

## Use Case 5 - Data Processing

### Description

Facilitate the processing of EO data through scalable and customisable environments. This use case supports the
execution of complex data processing workflows, enabling users to preprocess, transform, and analyse EO data
effectively.

### Key Components

* [**User Workspace**](user_workspace.md)\
Providing secure environments for executing data processing tasks on existing cloud-based processing platforms.
* [**Interactive Development Environment (IDE)**](ide.md)\
Supporting data processing scripts and workflows, including pre-configured tools for EO tasks.
* [**Product Catalogue**](catalog.qmd)\
Streamlined data ingestion and access to a wide range of EO datasets.
* **[Geospatial Explorer](geospatial_explorer.md) and Web Apps**\
Interactively visualise results.

```{mermaid}
%%| label: fig-tools-usecase5
%%| fig-cap: "APEx Project Tools - Data Processing"
flowchart TD ""
    subgraph Project Environment
      UW(User Workspace) --> |Activate| IDE(Interactive Development<br/> Environment)
    end
    subgraph Public Environment
      A(Project Portal) -->|Links to| B(Geospatial<br/>Explorer)
      B -->|Visualizes| C(Product<br/>Catalogue)
      A -->|Links to| C
    end

    IDE -->|Publish| C

    class UW,IDE,A,B,C apexService
    click A href "./project_portal.html" _blank
    click B href "./geospatial_explorer.html" _blank
    click C href "./catalog.html" _blank
    click UW href "./user_workspace.html" _blank
    click IDE href "./ide.html" _blank
```

### Expected Benefits

* Improved efficiency in data processing workflows.
* Scalable solutions for handling large volumes of EO data.
* Enhanced ability to preprocess and prepare data for analysis and visualisation.
