project:
  type: website
  preview:
    port: 4200

website:
  favicon: assets/img/logos/apex_icon_blue.svg
  repo-url: "https://github.com/ESA-APEx/apex_documentation"
  repo-branch: "main"
  search:
    location: sidebar
    type: textbox
    copy-button: true

  navbar:
    pinned: true
  page-navigation: true
  bread-crumbs: true

  title: "APEx - Documentation Portal"

  sidebar:
    style: "floating"
    contents:
      - href: index.qmd
        text: Welcome
      #      - href: eo_service_usage.qmd
      - section: On-demand EO services
        contents:
          - href: eo_service_usage/openeo_usage.md
            text: Using openEO service
          - href: propagation/platforms.md
      - href: instantiation/index.md
        section: Project Environments
        contents:
          - href: instantiation/usecases.qmd
            text: Use Cases
          - href: instantiation/customisation.md
          - href: instantiation/accessibility.md
          - href: instantiation/geospatial_explorer.md
          - href: instantiation/project_portal.md
          - href: instantiation/app_code_server.md
          - href: instantiation/app_jupyterlab.md
          - href: instantiation/app_qgis.md
          - href: instantiation/catalog.qmd
          - href: instantiation/documentation.qmd
          - href: instantiation/forum.md
      - href: propagation/index.qmd
        section: Algorithm Support
        contents:
          - href: propagation/ondemandservices.qmd
          - href: propagation/usecases.md
            text: Use Cases
          - href: propagation/porting.md
          - href: propagation/onboarding.md
          - href: propagation/upscaling.md
          - href: propagation/enhancement.md
          - href: propagation/toolboxcloud.md
          - href: propagation/intercomparison.md
      - section: Guides
        contents:
          - section: Developer Guides
            contents:
              - section: Authentication
                contents:
                  - href: guides/account.md
                  - href: guides/token.md
                    text: Creating APEx single sign-on token
              - section: openEO
                contents:
                  - href: guides/udp_writer_guide.qmd
                    text: Creating openEO based services
                  - href: guides/upscaling_openeo.ipynb
                    text: Upscaling openEO based services
              - section: EOAP
                contents:
                  - href: guides/eoap_writer_guide.md
                    text: Creating EOAP based services
              - section: APEx Product Catalogue
                contents:
                  - href: guides/stac_catalog_ingest.ipynb
                    text: Ingesting STAC metadata in APEx Product Catalogue
                  - href: guides/catalog_openeo.ipynb
                    text: Linking APEx Product Catalogue with an openEO service
              - section: APEx Algorithm Services Catalogue
                contents:
                  - href: guides/algorithm_services_catalogue.qmd
                  - href: guides/algorithm_services_catalogue_benchmarks.qmd
              - href: guides/file_formats.qmd
                text: File format recommendations
          - section: Admin Guides
            contents:
              - href: guides/account.md
              - href: guides/custom_domain.md
                text: Custom domains for your project environment
              - href: guides/geospatial_explorer/index.qmd
                contents:
                  - auto: guides/geospatial_explorer/tutorials/*.qmd
              - href: guides/project_portal/index.qmd
                contents:
                  - auto: guides/project_portal/tutorials/*.qmd

          - section: Consumer Guides
            contents:
              - href: guides/geospatial_explorer/geospatial_explorer_guide.qmd

      - href: interoperability/index.md
        section: Interoperability and Compliance Guidelines
        contents:
          - href: interoperability/definitions.qmd
          - href: propagation/service_development.qmd
          - href: interoperability/algohosting.md
          - href: interoperability/datahosting.md
          - href: interoperability/algohostingenv.md
          - href: interoperability/geospatial_explorer.qmd
          - href: interoperability/businessmodel.md

format:
  html:
    toc-depth: 4
    page-layout: full
    theme: [cosmo, css/custom.scss]
    scss: true
    highlight-style: solarized
    include-in-header:
      - html/apex-scripts.html
      - html/blur.html
      - html/esa-header.html
      - html/apex-navigation.html
      - html/apex-hamburger-menu.html
    link-external-newwindow: false
    bibliography: interoperability/references/references.yaml
    csl: interoperability/references/diabetologia.csl
