project:
  type: website
  preview:
    port: 4200

website:
  favicon: assets/img/logos/apex_icon_blue.svg
  repo-url: "https://github.com/ESA-APEx/apex_documentation"
  repo-branch: "main"
  search:
    location: sidebar
    type: textbox
    copy-button: true

  navbar:
    pinned: true
  page-navigation: true

  title: "APEx - Documentation Portal"

  sidebar:
    style: "floating"
    collapse-level: 2
    contents:
      - href: index.qmd
        text: Welcome
      #      - href: eo_service_usage.qmd
      - text: On-demand EO services
        contents:
          - href: eo_service_usage/openeo_usage.md
            text: Using openEO service
          - href: propagation/platforms.md
      - href: instantiation/index.md
        text: Project Tools
        contents:
          - href: instantiation/usecases.qmd
            text: Use Cases
          - href: instantiation/geospatial_explorer.md
          - href: instantiation/project_portal.md
          - href: instantiation/user_workspace.md
          - href: instantiation/ide.md
          - href: instantiation/catalog.qmd
          - href: instantiation/documentation.qmd
          - href: instantiation/forum.md
      - href: propagation/index.qmd
        text: Algorithm Services
        contents:
          - href: propagation/ondemandservices.qmd
          - href: propagation/usecases.md
            text: Use Cases
          - href: propagation/porting.md
          - href: propagation/onboarding.md
          - href: propagation/upscaling.md
          - href: propagation/enhancement.md
          - href: propagation/toolboxcloud.md
          - href: propagation/intercomparison.md
      - text: Guides
        contents:
          - href: guides/account.md
          - href: guides/token.md
            text: Creating APEx single sign-on token
          - href: guides/udp_writer_guide.qmd
            text: Creating openEO based services
          - href: guides/eoap_writer_guide.md
            text: Creating EOAP based services
          - href: guides/upscaling_openeo.ipynb
            text: Upscaling openEO based services
          - href: guides/stac_catalog_ingest.ipynb
            text: Ingesting STAC metadata in APEx Product Catalogue
          - href: guides/catalog_openeo.ipynb
            text: Linking APEx STAC catalogue with an openEO service
          - href: guides/file_formats.qmd
            text: File format recommendations
          - href: guides/geospatial_explorer_guide.md
            text: Using the Geospatial Explorer

      - href: interoperability/index.md
        text: Interoperability and Compliance Guidelines
        contents:
          - href: interoperability/definitions.qmd
          - href: propagation/service_development.qmd
          - href: interoperability/algohosting.md
          - href: interoperability/algohostingenv.md
          - href: interoperability/geospatial_explorer.md
          - href: interoperability/businessmodel.md

format:
  html:
    toc-depth: 4
    page-layout: full
    theme: [cosmo, css/custom.scss]
    scss: true
    highlight-style: solarized
    include-in-header:
      - html/apex-scripts.html
      - html/blur.html
      - html/esa-header.html
      - html/apex-navigation.html
      - html/apex-hamburger-menu.html
    link-external-newwindow: false
    bibliography: interoperability/references/references.yaml
    csl: interoperability/references/diabetologia.csl
bread-crumbs: true
