project:
  type: website

website:
  favicon: _images/logos/favicon.png
  repo-url: "https://github.com/ESA-APEx/apex_documentation"
  repo-branch: "main"
  search:
    location: sidebar
    type: textbox
    copy-button: true

  navbar:
    pinned: true
  page-navigation: true

  title: "APEx - Documentation Portal"

  sidebar:
    style: "floating"
    collapse-level: 2
    contents:
      - href: index.qmd
        text: Welcome
      - href: eo_service_usage.qmd
        text: On-demand EO services
        contents:
          - href: eo_service_usage/openeo_usage.md
            text: Using openEO service
      - href: instantiation/index.md
        text: Instantiation Services
      - href: propagation.md
        text: EO Service Support
        contents:
          - href: propagation/hosting.md
            text: Algorithm Hosting
          - href: propagation/upscaling.md
            text: Algorithm Upscaling
          - href: propagation/enhancement.md
            text: Algorithm Enhancement
          - href: propagation/toolboxcloud.md
            text: Toolbox Cloudification
          - href: propagation/intercomparison.md
            text: Algorithm Intercomparison
      - href: udp_writer_guide.qmd
        text: Creating openEO based services
      - href: interoperability/index.md
        text: Interoperability and Compliance Guidelines
        contents:
          - href: interoperability/definitions.md
          - href: interoperability/references.md
          - href: interoperability/algohosting.md
          - href: interoperability/algohostingenv.md
          - href: interoperability/dashboards.md
          - href: interoperability/businessmodel.md

format:
  html:
    toc: true
    toc-depth: 4
    page-layout: full
    theme: [cosmo, css/custom.scss]
    highlight-style: solarized
    include-in-header:
      - html/blur.html
      - html/esa-header.html
bread-crumbs: true