project:
  type: website

website:
  favicon: _images/logos/favicon.png
  repo-url: "https://github.com/ESA-APEx/apex_documentation"
  repo-branch: "main"
  search:
    location: sidebar
    type: textbox
    copy-button: true

  navbar:
    pinned: true
  page-navigation: true

  title: "APEx - Documentation Portal"

  sidebar:
    style: "floating"
    collapse-level: 2
    contents:
      - href: index.qmd
        text: Welcome
      - href: eo_service_usage.md
        text: On-demand EO services
        contents:
          - href: eo_service_usage/openeo_usage.md
            text: Using openEO service
      - href: propagation.md
        text: EO Service Support
        contents:
          - href: propagation/hosting.md
            text: Algorithm Hosting
          - href: propagation/upscaling.md
            text: Algorithm Upscaling
          - href: propagation/enhancement.md
            text: Algorithm Enhancement
          - href: propagation/toolboxcloud.md
            text: Toolbox Cloudification
          - href: propagation/intercomparison.md
            text: Algorithm Intercomparison
      - href: interoperability.md
        text: Interoperability and Compliance Guidelines
        contents:
          - href: interoperability/algohosting.md
            text: Algorithm Hosting
          - href: interoperability/algohostingenv.md
            text: Algorithm Hosting Environments
          - href: interoperability/dashboards.md
            text: Dashboards

format:
  html:
    toc: true
    toc-depth: 4
    page-layout: full
    theme: cosmo
    css: custom.scss
bread-crumbs: true