project:
  type: website

website:
  favicon: assets/img/logos/apex_icon_blue.svg
  repo-url: "https://github.com/ESA-APEx/apex_documentation"
  repo-branch: "main"
  search:
    location: sidebar
    type: textbox
    copy-button: true

  navbar:
    pinned: true
  page-navigation: true

  title: "APEx - Documentation Portal"

  sidebar:
    style: "floating"
    collapse-level: 2
    contents:
      - href: index.qmd
        text: Welcome
      - href: eo_service_usage.qmd
        text: On-demand EO services
        contents:
          - href: eo_service_usage/openeo_usage.md
            text: Using openEO service
      - href: instantiation/index.md
        text: Instantiation Services
        contents:
          - href: instantiation/usecases.md
            text: Use Cases
      - href: propagation/index.qmd
        text: Algorithm Propagation
        contents:
          - href: propagation/porting.md
            text: Algorithm Porting
          - href: propagation/onboarding.md
            text: Algorithm Onboarding
          - href: propagation/upscaling.md
            text: Algorithm Upscaling
          - href: propagation/enhancement.md
            text: Algorithm Enhancement
          - href: propagation/toolboxcloud.md
            text: Toolbox Cloudification
          - href: propagation/intercomparison.md
            text: Algorithm Intercomparison
          - href: propagation/usecases.md
            text: Use Cases
      - href: udp_writer_guide.qmd
        text: Creating openEO based services
      - href: interoperability/index.md
        text: Interoperability and Compliance Guidelines
        contents:
          - href: interoperability/definitions.qmd
          - href: interoperability/references.md
          - href: interoperability/algohosting.md
          - href: interoperability/algohostingenv.md
          - href: interoperability/geospatial_explorer.md
          - href: interoperability/businessmodel.md

format:
  html:
    toc-depth: 4
    page-layout: full
    theme: [cosmo, css/custom.scss]
    scss: true
    highlight-style: solarized
    include-in-header:
      - html/apex-scripts.html
      - html/blur.html
      - html/esa-header.html
      - html/apex-navigation.html
      - html/apex-hamburger-menu.html
    link-external-icon: true
    link-external-newwindow: true
bread-crumbs: true
