---
title: Geospatial Explorer
---

This section outlines the requirements for the interoperability of the APEx Geospatial Explorer services. These
requirements must be met to ensure the correct configuration and operation of a dashboard and its instantiation.

A technical challenge of the Geospatial Explorer service being provided by APEx is that it is to be instantiated on
demand, with functional requirements potentially varying amongst each service.The geospatial explorer makes ue of a
well-defined configuration schema, provided in the form of JSON, that outlines the interactive features and
data sources to be used.

This approach allows APEx to define and update the schema required in the interoperability guidelines, which will
then enables requesters of the service to configure the Geospatial Explorer on an individual project level with minimal
external intervention.

The schema is versioned as it will change throughout the APEx project as the functional capabilities of the
Geospatial Explorer matures. This does allow for improvements and extra features to be easily added to the application,
and best practices shall be followed to avoid any breaking changes between versions.

## Requirements

@tbl-geoexplorer outlines the requirements for configuring an instance of the Geospatial Explorer application.

::: {#tbl-geoexplorer .tbl}
<table class="requirements">
  <thead>
    <tr>
      <th>ID</th>
      <th>Requirement</th>
      <th>Description</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>EXPLORER-REQ-01</td>
      <td>Configuration of the Geospatial Explorer shall adhere to the provided JSON schema, as described in the [Configuration Schema](#configuration-schema) section.</td>
      <td>The application is configured through a hosted JSON object which is fetched when the client-side application loads.
      For the application to correctly render, a valid configuration JSON that follows the outlined schema must be provided
      pre-instantiation. During early development the schema will be subject to change and provided with limited validation.</td>
    </tr>
    <tr>
      <td>EXPLORER-REQ-02</td>
      <td>
        Raster sources defined within the config shall be provided as either:
        <ul>
          <li>A well formed URL to a hosted Cloud Optimised GeoTiff (COG) [@cog].</li>
          <li>A well formed URL pointing to STAC item containing a publicly hosted Cloud Optimised Geotiff as an asset.</li>
          <li> WMS [@wms] or WMTS [@wmts] endpoint following the relevant OGC specifications.</li>
          <li>A template URL following the XYZ(*) format serving PNG or JPEG tiles.</li>
        </ul>
      </td>
      <td>The use of these formats ensures that raster data can be visualized using widely recognized and well-established
      standards.</td>
    </tr>
    <tr>
      <td>EXPLORER-REQ-03</td>
      <td>
        Vector sources defined within the config shall be provided as either:
        <ul>
          <li>A well formed URL to a valid GeoJSON [@geojson] resource.</li>
          <li>A public WFS [@wfs] or OGC API Features [@ogc_features] endpoint following the relevant OGC specifications.</li>
          <li> A well formed URL to a valid FlatGeobuf [@flatgeobuf] resource.</li>
        </ul>
      </td>
      <td>The use of these formats ensures that vector data can be visualized using widely recognized and well-established
      standards.</td>
    </tr>
    <tr>
      <td>EXPLORER-REQ-04</td>
      <td>All external sources shall be publicly available or accessible via an APEx user token.</td>
      <td>The Geospatial Explorer will need to fetch any configured data directly from a source server. It is expected
      that these resources can be accessed directly through a HTTP request that is either open access (No authentication
      requirements) or can be authenticated using an APEx user bearer token via the HTTP Authentication header.</td>
    </tr>
    <tr>
      <td>EXPLORER-REQ-05</td>
      <td>All external sources shall be available utilising the HTTPS protocol.</td>
      <td>It is best practice to utilise HTTPS where possible. Whilst not as of yet blocked specifically, non-secure
      resources may not function correctly.</td>
    </tr>
    <tr>
      <td>EXPLORER-REQ-06</td>
      <td>Web service endpoints for data must be configured to allow cross-origin requests from the domain hosting the
      Geospatial Explorer.</td>
      <td>This includes setting the Access-Control-Allow-Origin header to explicitly permit the origin of the requesting
      front end or using a dynamic or wildcard origin setting if appropriate. Additionally, the web service must handle
      preflight (OPTIONS) requests correctly, including the Access-Control-Allow-Methods and Access-Control-Allow-Headers
      headers, to support the HTTP methods and headers used by the front end.</td>
    </tr>
    <tr>
      <td>EXPLORER-REQ-07</td>
      <td>For optimal visualisation performance, datasets should be projected into the same CRS as the display CRS used
      for the Geospatial Explorer. </td>
      <td>
        <p>Where the CRS is not the same as the display CRS in the Geospatial Explorer, data will be reprojected “on the
        fly”, with a performance impact for display that will depend on the complexity of the projection transformation
        between dataset and Geospatial Explorer display CRS’s.</p>
        <p>All Geospatial Explorer instances will support the following projections which can be used as the display CRS
        and / or any of the data CRS’s</p>
        <ul>
          <li>WGS 84 / Spherical Mercator (EPSG:3857) - "Web Mercator"</li>
          <li>WGS 84 / Geographic (EPSG:4326)</li>
          <li>WGS 84 / UTM zones (EPSG:32601 to EPSG:32660 for northern zones, EPSG:32701 to EPSG:32760 for southern zones)</li>
          <li>ETRS89-extended / LAEA Europe (EPSG:3035)</li>
          <li>WGS 84 / NSIDC Sea Ice Polar Stereographic North (EPSG:3413)</li>
          <li>WGS 84 / Antarctic Polar Stereographic (EPSG:3031)</li>
        </ul>
        <p>In addition it is possible to support any projection supported by the PROJ4JS library [@proj4js] by
        configuring an appropriately formatted projection string in the Geospatial Explorer JSON configuration file,
        which can be done via the Configuration Builder (CB) tool. </p>
        <p>**Note**: APEx recommends datasets should be provided in a single, standardised projection system that covers
        the full spatial extent of the data. Fragmented projections (e.g. UTM across multiple zones) should be avoided
        as they introduce complexity, reduce performance, and limit key Geospatial Explorer functionalities.</p>
      </td>
    </tr>
    <tr>
      <td>EXPLORER-REQ-08</td>
      <td>Where WM(T)S is used, its sources should declare their projection through the GetCapabilities request.</td>
      <td>This ensures that the Geospatial Explorer renders the data in the corresponding projection and prevents
      unnecessary on-the-fly reprojections.</td>
    </tr>
    <tr>
      <td>EXPLORER-REQ-09</td>
      <td>
        <p>Legends support is provided in the Geospatial Explorer via the following mechanisms:</p>
        <ul>
          <li>Dynamically using “swatch” or “gradient” options in the Geospatial Explorer config, which displays a
          legend using category, gradient or colormap settings;</li>
          <li>By calling a WMS [@wms] getLegendGraphic request (if supported by a WMS source)</li>
          <li>By specifying in config the URL to a browser supported image resource (PNG, JPEG, SVG).</li>
        </ul>
        <p>Legend settings can be configured using the Configuration Builder tool.</p>
      </td>
      <td>This guideline ensures that the legend is fully compatible with the visualisation library used in the Geospatial
      Explorer.</td>
    </tr>
    <tr>
      <td>EXPLORER-REQ-10</td>
      <td>Statistical datasets   should be configured by providing public URLs to either: GeoJSON [@geojson] or
      FlatGeobuf [@flatgeobuf]. Details on the structure of these datasets are outlined in the [Data Provider Guidelines](../interop) section.</td>
      <td>The statistics feature is complex due to the architecture and requirements of the Geospatial Explorer. Statistical datasets contain one or more files that include vector features that describe an area and the relevant statistics for the area can be added to the configuration of an explorer instance. </td>
    </tr>
    <tr>
      <td>EXPLORER-REQ-11</td>
      <td>
        <p>To facilitate the integration of STAC datasets within the Geospatial Explorer, it is advisable to follow the recommendations presented in our [metadata recommendations](./datahosting.md#metadata-recommendations). For optimal results within the Geospatial Explorer, the use of the following STAC extensions is recommended:</p>
        <ul>
          <li>[classification extension](https://github.com/stac-extensions/classification)</li>
          <li>[render extension](https://github.com/stac-extensions/render)</li>
        </ul>
      </td>
      <td>The usage of the suggested extensions will allow the Geospatial Explorer to automatically configure the visualization properties of the selected dataset without the need for additional manual configuration.</td>
    </tr>
    <tr>
      <td>EXPLORER-REQ-12</td>
      <td>“Secondary” constraint layers (e.g. elevation; land cover) can be used to filter the data in a “primary” layer (e.g. solar energy potential).  Both the primary and secondary layers need to be Cloud Optimised GeoTIFFs. All primary and secondary layers must use the same grid (i.e. CRS, origin and resolution) as each other.</td>
      <td></td>
    </tr>
  </tbody>
</table>
Interoperability requirements for the Geospatial Explorer application
:::

(*) The XYZ approach refers to a de facto API standard for URL structuring (Z = zoom level, X and Y = grid references).
While there is no dedicated specification for XYZ, it is widely used (e.g., [OpenStreetMap](https://wiki.openstreetmap.org/wiki/Raster_tile_providers)).

## Format Specification & Guidelines

For further guidance on visualising data in the APEx Geospatial Explorer, it is highly recommended to follow the
[recommendations](../interoperability/datahosting.qmd#scenario-3-visualisation-in-apex-geospatial-explorer). This
scenario outlines the best practices for ensuring datasets are optimally configured and compatible with the Explorer’s
visualisation features.

## Configuration Schema

The service configuration will be based on a schema that provides administrators with the expected structure and contents
of the configuration. Taking this approach enables:

* Automated and dynamic instantiation of the service with differing functionality.
* Configuration validation.
* Definition of a “contract” for easier documentation of features and their configuration.

For more detailed information on this configuration schema, refer to the APEx documentation portal:
[APEx Configuration Schema Documentation](../guides/geospatial_explorer/tutorials/geospatial_explorer_config_guide.qmd).
Numerous example configurations can be found in the
[APEx Geospatial Explorer Configurations](https://github.com/ESA-APEx/apex_geospatial_explorer_configs) repository on
GitHub.
