name: Publish content to GitHub pages
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
concurrency: publish

jobs:
  build-documentation:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          tinytex: true
          version: '1.4.554'
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Install dependencies
        run: pip install jupyter && pip install -r requirements.txt
      - name: Render documentation pages
        run: quarto render --output-dir _build
      - name: Setup GitHub pages
        uses: actions/configure-pages@v3
      - name: Upload build artifacts
        uses: actions/upload-pages-artifact@v1
        with:
          path: "_build"
      - name: Upload build folder
        uses: actions/upload-artifact@v3
        with:
          name: build-folder
          path: "_build"
  
  documentation-quality-checks:
    runs-on: ubuntu-latest
    needs: build-documentation
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Check broken links 
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: 'yes'
          config-file: 'markdown-link-checker-config.json'

  deploy-documentation-ghpages:
    runs-on: ubuntu-latest
    needs: documentation-quality-checks
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub pages
        id: deployment
        uses: actions/deploy-pages@v2

  deploy-documentation-branch:
    runs-on: ubuntu-latest
    needs: documentation-quality-checks
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    permissions:
      contents: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set Git config
      run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Actions"

    - name: Download build folder
      uses: actions/download-artifact@v3
      with:
        name: build-folder
        path: ./_build

    - name: Commit and Push to docportal branch
      run: |
          git checkout docportal  || git checkout --orphan docportal
          git rm -rf .
          echo '_build/' >> .gitignore
          cp -r _build/* .
          git add .
          git commit -m "chore: update of documentation"
          git push --force origin docportal
